config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  ActiveAdmin.routes(self)
  resources :lands, only: [:index, :show, :destroy] do
    collection { post :import }
    resources :comments, only: [:create]
  end
  get 'pages/home' => 'pages#home'

  devise_for :users
  root to: 'lands#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :land
  belongs_to :user
end

app/models/land.rb
class Land < ActiveRecord::Base

  validates :number, presence:true
  validates :surface, presence: true
  validates :address, presence: true
  validates :neighborhood, presence: true
  validates :city, presence: true
  validates :file, presence:true

  has_many :comments



  # geocoded_by :full_street_address
  # after_validation :geocode, if: :address_changed?

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Land.create! row.to_hash
     end
  end

  def full_street_address
    [address, city].compact.join(', ')
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :comments


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_land

  def create
    @comment = Comment.new(comment_params)
    @comment.land = @land
    @comment.user = current_user
      if @comment.save
        redirect_to land_path(@land)
      else
        render :show
      end
  end

  private

  def set_land
    @land = Land.find(params[:land_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/lands_controller.rb
class LandsController < ApplicationController
  before_action :set_land, only: [:show, :destroy]
  def index
    @lands = Land.all.paginate(:page => params[:page], :per_page => 10)
    @lands = @lands.where(city: params[:city]) if params["city"].present?
    @lands = @lands.where(neighborhood: params[:neighborhood]) if params["neighborhood"].present?
    @lands = @lands.where("surface >= ?", params[:min_surface]) if params["min_surface"].present?
    @lands = @lands.where("surface <= ?", params[:max_surface]) if params["max_surface"].present?
    # @land_coordinates = { lat: @land.latitude, lng: @land.longitude }
    # Let's DYNAMICALLY build the markers for the view.
    end

    def home

    end


  def show
    @hash = Gmaps4rails.build_markers(@land) do |land, marker|
      marker.lat land.latitude
      marker.lng land.longitude
    end

    @comment = Comment.new
  end

  def import
  Land.import(params[:file])
  redirect_to lands_path, notice: "Les parcelles ont été ajoutées !!"
  end

  def destroy
    @land.destroy
      redirect_to lands_path
  end

  private

  def set_land
    @land = Land.find(params[:id])
  end

  def land_params
    params.require(:land).permit(:number, :surface, :address, :neighborhood, :city, :latitude, :longitude, :file, :comment)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/views/lands/home.html.erb
<div class="jumbotron">
  <h2 class="text-center">All you need is business !</h2>

<%= render 'shared/filter' %>
</div>

app/views/lands/index.html.erb
<div class="container">
  <%= render 'shared/filter' %>

  <br>

  <% if @lands.empty? %>
    <h3> Il n'y a pas de terrains correspondant à votre recherche </h3>
  <% else %>
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="text-center">Nous avons trouvé <%= @lands.count %> propriété(s) potentiels correspondant à votre recherche</h4>
          </div>
          <div class="panel-body">
            <% @lands.each do |land| %>
              <div class="row">
                <div class="col-md-2">
                  <%= land.surface %> m2
                  <p> Fichier n°<%= land.file %></p>
                </div>
                <div class="col-md-4">
                  <h4 class="mt-0"><%= land.address %></h4>

                </div>
                <div class="col-md-4">
                  <p><%= land.neighborhood %></p>
                </div>
                <div class="col-md-2 right">
                  <p><%= link_to "En savoir plus", land_path(land) %></p>
                </div>
              </div>
              <div class= "row">
                <div class="col-md-12">
                  <%= image_tag("http://maps.googleapis.com/maps/api/streetview?key=AIzaSyCwCp3To_EfAyq9Yt0-x9O2KfQMU4dLRw8&size=640x400&location=#{land.full_street_address}&fov=180&&pitch=1&sensor=false", class: "item-show-map")%>
                  <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?key=AIzaSyCwCp3To_EfAyq9Yt0-x9O2KfQMU4dLRw8&zoom=15&size=450x400&sensor=false&maptype=roadmap&markers=color:red|#{land.full_street_address}", class: "item-show-map" %>
                </div>
              </div>
              <% if current_user.try(:admin?) %>
               <%= link_to "Effacer", land_path(land), method: :delete %>
              <% end %>
              <br><hr><br>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/lands/show.html.erb
<br>
 <div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>Vue extérieure du <%= @land.full_street_address %></h4>
        </div>
        <div class="panel-body">

          <div id="map2" class="map_show"></div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>Plan du <%= @land.full_street_address %></h4>
        </div>
        <div class="panel-body">

          <div id="map3" class="map_show"></div>

        </div>
      </div>
      <div class="panel-body">
              <% if @land.comments.blank? %>
                <h3> Soyez le premier à inserer un commentaire pour cette parcelle </h3>
              <% else %>
                <% @land.comments.each do |comment| %>
                  <div class="row">
                    <div class="col-md-2">
                      <%= comment.created_at.strftime('%d %B') %>
                    </div>
                    <div class="col-md-2">
                      <%= "#{comment.user.first_name.capitalize}" %>
                    </div>

                    <div class="col-md-8">
                      <%= comment.content %>
                    </div>
                  </div>
                <% end %>
              <% end %>
              <%= simple_form_for [@land, @comment] do |f| %>
                <%= f.text_area :content, rows:5, placeholder: "Inserer votre commentaire ici", class: "form-control mt-20" %>
                <div class="text-center mt-20">
                  <%= f.button :submit, class:"btn btn-primary" %>
                </div>
              <% end %>
            </div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
      $(document).on('ready', function() {

        pos = new google.maps.LatLng( <%= @land.latitude %>, <%= @land.longitude %> );

var div = document.getElementById('map2');
var sv = new google.maps.StreetViewPanorama(div);
sv.setPosition( pos );
sv.setVisible( true );

// find the heading by looking from the google car pos to the venue pos
var service = new google.maps.StreetViewService();
service.getPanoramaByLocation( pos, 50, function(result, status) {
    if (status == google.maps.StreetViewStatus.OK)
    {
        carPos = result.location.latLng;
        heading = google.maps.geometry.spherical.computeHeading( carPos, pos );
        sv.setPov( { heading: heading, pitch: 0, zoom: 1 } );
    }
    else {
    console.log('Street View Noet Available');
  }
} );
      })
    <% end %>
  <% end %>

  <% content_for(:after_js) do %>
  <%= javascript_tag do %>
      $(document).on('ready', function() {

        handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map3' }
        }, function(){
          markers = handler.addMarkers(<%= raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          handler.getMap().setZoom(15);
        });
      })
    <% end %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?sensor=false&key=AIzaSyCwCp3To_EfAyq9Yt0-x9O2KfQMU4dLRw8" %>
    <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places" %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h3>Import Lands</h3>
<%= form_tag import_lands_path, multipart: true do %>
  <span class="btn btn-large btn-warning btn-file">
    Choose File
    <%= file_field_tag :file %>
  </span>
  <%= submit_tag "Upload Companies", class: "btn btn-primary" %>
<% end %>

app/views/shared/_filter.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-12">
        <div class="filter">
          <br>
          <%= form_tag lands_path, method: :get, class: "text-center" do %>



            <div class="col-md-3">
              <%= select_tag(:neighborhood,options_for_select(['PARC-SAINT-MAUR','SAINT-MAUR-CRETEIL','VIEUX-SAINT-MAUR','ADAMVILLE', 'LA PIE','LES MURIERS', 'LA VARENNE SAINT HILAIRE', 'CHAMPIGNOL'], params[:neighborhood]), prompt: "Choisissez un quartier", class: "form-control") %>

            </div>

            <div class="col-md-3">
              <%= text_field_tag :min_surface, params[:min_surface], placeholder:"Surface minimum", class: "form-control"%>
            </div>

            <div class="col-md-3">
              <%= text_field_tag :max_surface, params[:max_surface], placeholder:"Surface maximum", class: "form-control" %>
            </div>

            <div class="col-md-3">
              <%= submit_tag "Recherche", name: nil, class: "btn btn-primary" %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <a href="/">
      <h1 class="logo">L'arme fatale</h1>
    </a>

    <div class="navbar-wagon-pusher"></div>


    <hr class="hidden-xs hidden-sm">
    <% if user_signed_in? %>

      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= current_user.email %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-user"></i> <i   class="glyphicon glyphicon-chevron-down"></i></a>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "/" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <hr>
    <% if current_user.try(:admin?) %>
      <%= link_to t(".top_call_to_action", default: "Post stuff"), pages_home_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>
  </div>
</nav>